In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('play_tennis.csv')
data.drop(columns=['day'],inplace=True)
data.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

### Make look up table

In [4]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [5]:
# P(Yes)
# P(No)

py = 9 / 14
pn = 5 / 14

In [6]:
# Outlook

pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [7]:
Pon = 0
Prn = 2 / 5
Psn = 3 / 5

Poy = 4 / 9 
Pry = 3 / 9
Psy = 2 / 9

In [8]:
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [9]:
PcoolNo = 1 / 5
PhotNo = 2 / 5
PmildNo = 2 / 5

PcoolYes = 3 / 9
PhotYes = 2 / 9
PmildYes = 4 / 9

In [11]:
# humidity
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [12]:
PhighNo = 4 / 5
PnormalNo = 1 / 5

PhighYes = 3 / 9
PnormalYes = 6 / 9

In [13]:
# wind
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [18]:
PstrongNo = 3 / 5
PweekNo = 2 / 5

PstrongYes = 3 / 9
Pweekyes =  6 / 9

In [16]:
# outlook = sunny,temp = hot,humidity = high, wind = weak

pyes = py *  Psy * PhotYes * PhighYes * Pweekyes
pyes

0.007054673721340388

In [19]:
pno = pn *  Psn * PhotNo * PhighNo * PweekNo
pno

0.02742857142857143